# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joey Day
author: Joey Day
description: > # this means to ignore newlines until "baseurl:"
    Hi, I’m Joey. I’m a 30-something software engineer (read: big nerd) in Salt Lake
    City. When I grow up I’d like to be a seminary professor (read: even bigger nerd).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/joeyday/joeyday.com" # the base hostname & protocol for your site, e.g. http://example.com
# google_analytics: UA-103818339-1

# Social media
twitter_username: joeyday
facebook_username: joeynday
github_username:  joeyday

# Build settings
markdown: kramdown
# highlighter: rouge
theme: jekyll-theme-minimal
permalink: /joeyday.com/:year/:month/:day/:title/
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
